CREATE TABLE IF NOT EXISTS test_methods (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    legacy_number VARCHAR(100),
    legacy_lab_source VARCHAR(100),
    original_title VARCHAR(255) NOT NULL,
    official_number VARCHAR(50) UNIQUE,
    official_title VARCHAR(255),
    category_id UUID,
    method_type VARCHAR(100),
    status VARCHAR(50) DEFAULT 'draft',
    verification_status VARCHAR(50) DEFAULT 'pending',
    verified_by UUID,
    verified_date DATE,
    verification_notes TEXT,
    purpose TEXT,
    scope TEXT,
    principle TEXT,
    equipment_required TEXT,
    reagents_required TEXT,
    procedure TEXT,
    calculations TEXT,
    acceptance_criteria TEXT,
    method_references TEXT,
    current_version VARCHAR(20) DEFAULT '1.0',
    version_notes TEXT,
    supersedes_method_id UUID,
    superseded_by_method_id UUID,
    effective_date DATE,
    review_date DATE,
    next_review_date DATE,
    created_by UUID,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
